title: On-going
description: >
 **On-going** is een blog over onderweg zijn. Intussen is dat **3.145** km in **12** landen.
copyright: On-going
sass:
  sass_dir: assets/sass
url: https://bramm.github.io/
disqus_shortname:
facebook_username: bram.smers
twitter_username:
linkedin_username:
instagram_username:
strava_username: athletes/bsmers
flickr_username:
github_username:  "Bramm"
feed_icon: rss
email: "bram@seasoning.be"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
