title: On-going
description: >
 **On-going** is een blog over onderweg zijn. Uiteindelijk zo'n **4.116** km in **12** landen.
copyright: On-going
sass:
  sass_dir: assets/sass
url: https://on-going.org
disqus_shortname: https-bramm-github-io
facebook_username: bram.smers
twitter_username:
linkedin_username:
instagram_username:
strava_username: athletes/bsmers
flickr_username:
github_username:  "Bramm"
feed_icon:
email: "somersbram@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
