title: Strata by HTML5 UP
description: >
  **I am Strata**, a super simple<br />
  responsive site template freebie<br />
  crafted by [HTML5 UP](http://html5up.net).
copyright: Untitled
sass:
  sass_dir: assets/sass
permalink: none
url: http://example.com
twitter_username: "#"
github_username:  "#"
email: "#"
