title: Strata by HTML5 UP
description: >
  <strong>I am Strata</strong>, a super simple<br />
  responsive site template freebie<br />
  crafted by <a href="http://html5up.net">HTML5 UP</a>.
copyright: Untitled
sass:
  sass_dir: assets/sass
permalink: none
url: http://example.com
baseurl: 
