title: Strata by HTML5 UP
description: >
  **I am Strata**, a super simple<br />
  responsive site template freebie<br />
  crafted by [HTML5 UP](http://html5up.net).
copyright: Untitled
sass:
  sass_dir: assets/sass
permalink: none
url: http://example.com
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
